INTERACTIVE_MODELS_PATH: "experiments/sbd/"
EXPS_PATH: "experiments"

# Evaluation datasets
GRABCUT_PATH: "datasets/TestSet/GrabCut"
BERKELEY_PATH: "datasets/TestSet/Berkeley"
DAVIS_PATH: "datasets/TestSet/DAVIS"
COCO_MVAL_PATH: "datasets/TestSet/COCO_MVal"
COCO_MVAL_SEEN_PATH: "datasets/TestSet/COCO_MVal_seen"
COCO_MVAL_UNSEEN_PATH: "datasets/TestSet/COCO_MVal_unseen"

# Train datasets
SBD_PATH: "datasets/SBD"
# COCO_PATH: "datasets/coco2017"
# LVIS_PATH: "datasets/LVIS/label"
COCO_PATH: "/public/home/renhui/code/zhangchy2data/datasets/COCO"
LVIS_PATH: "/public/home/renhui/code/zhangchy2data/datasets/LVIS/label"
OPENIMAGES_PATH: "datasets/OpenImages"
PASCALVOC_PATH: "datasets/TestSet/VOC2012"

ADE20K_PATH: "datasets/ADE20K"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "/public/home/renhui/code/dataset/checkpoints/hrnetv2_w18_imagenet_pretrained.pth"
  SEGFORMER_B0: "/public/home/renhui/code/dataset/checkpoints/segformer/mit_b0.pth"
  SEGFORMER_B1: "/public/home/renhui/code/dataset/checkpoints/segformer/mit_b1.pth"
  SEGFORMER_B2: "/public/home/renhui/code/dataset/checkpoints/segformer/mit_b2.pth"
  SEGFORMER_B3: "/public/home/renhui/code/dataset/checkpoints/segformer/mit_b3.pth"
  SEGFORMER_B4: "/public/home/renhui/code/dataset/checkpoints/segformer/mit_b4.pth"
  SEGFORMER_B5: "/public/home/renhui/code/dataset/checkpoints/segformer/mit_b5.pth"
  # HRNETV2_W32: "pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  # HRNETV2_W40: "pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  # HRNETV2_W48: "pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
